name: Bug Report
description: Creat a report to help as improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: '40637323'
body:  
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. bugreportsystem@universal.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is and when the bug happens.
      placeholder: Tell us what you see!
    validations:
      required: true
- type: textarea
  id: reproduce-bug
  attributes:
      label: Steps required to reproduce the bug
      description: A clear and concise steps to reproduce the bug.
      placeholder: Tell us what are the steps to reproduce the bug!
    validations:
      required: true
- type: textarea
  id: screenshots
  attributes:
      label: ScreenShot for Relevant log output of Bug
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
- type: textarea
  id: expected-behavior
  attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: tell us what you want to see!
    validations:
      required: true
- type: dropdown
  id: browsers
  attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
- type: dropdown
  id: desktop
  attributes:
      label: What desktop are you seeing the problem on?
      multiple: true
      options:
        - windows
        - Linux
        - Mac
- type: dropdown
  id: smartphone
  attributes:
      label: What smartphone are you seeing the problem on?
      multiple: true
      options:
        - device
        - OS 
        - Browser
        -Version
- type: textarea
  id: additional-context
  attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: tell us freely!
    validations:
      required: true
- type: checkboxes
  id: terms
  attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://universal.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        
